# Generated by Django 4.0.6 on 2022-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_profile_img_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='università',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
