# Generated by Django 4.0.6 on 2022-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
