# Generated by Django 4.0.6 on 2022-11-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_max_pers',
            field=models.IntegerField(default=0),
        ),
    ]
