# Generated by Django 4.0.6 on 2023-03-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_post_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank_profile.jpg', upload_to='post_images'),
        ),
    ]
