# Generated by Django 4.0.6 on 2023-03-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_postimage_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
