# Generated by Django 4.0.6 on 2023-03-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
