# Generated by Django 4.0.6 on 2023-03-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank_profile.jpg', upload_to='post_images'),
        ),
    ]
