# Generated by Django 4.0.6 on 2023-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
