# Generated by Django 4.0.6 on 2023-03-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_postimage_image_rename_images_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
    ]
