# Generated by Django 4.0.6 on 2023-03-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_image_image_image_images_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='post_image',
        ),
    ]
