# Generated by Django 4.0.6 on 2023-03-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_postimage_rename_post_image_post_image_delete_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='images',
        ),
    ]
