# Generated by Django 4.0.6 on 2023-04-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_post_image_postfilecontent_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.DeleteModel(
            name='PostFileContent',
        ),
    ]
