# Generated by Django 4.0.6 on 2023-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_post_content_delete_postfilecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
