# Generated by Django 4.0.6 on 2023-04-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_profile_name_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
