# Generated by Django 4.0.6 on 2023-06-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_post_email_post_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
