# Generated by Django 4.0.6 on 2023-06-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_post_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(default='noimages.jpg', upload_to='post_images'),
        ),
    ]
