# Generated by Django 4.0.6 on 2023-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_postimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(default='blank_profile.jpg', upload_to='post_images'),
        ),
    ]
