# Generated by Django 4.0.6 on 2023-06-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
