# Generated by Django 4.0.6 on 2023-07-13 09:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=15, region=None),
        ),
    ]
